name: For Matrix Strategy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [24, 25]     # This creates 6 jobs (3 OS × 2 Node versions)

    steps:
      - uses: actions/checkout@v6
      
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - run: node --version
        
